services:
  - type: web
    name: smartspend
    env: python
    buildCommand: "cd frontend && npm install && npm run build && cd ../backend && pip install -r requirements.txt"
    startCommand: "cd backend && PYTHONPATH=..:. gunicorn --bind 0.0.0.0:$PORT 'app:create_app()'"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: PYTHONPATH
        value: "/opt/render/project/src:/opt/render/project/src/backend"
